const config=window.SAHARA_CONFIG||{};
const booking=document.querySelector('#booking');
function validUrl(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:null}catch{return null}}
document.querySelectorAll('[data-book]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.format)bookingState.format=b.dataset.format;if(!liveBooking)renderBooking(0);booking.showModal()}));
document.querySelector('.close').addEventListener('click',()=>booking.close());
document.querySelector('#booking-close').addEventListener('click',()=>booking.close());
booking.addEventListener('click',e=>{if(e.target===booking){const r=booking.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)booking.close()}});
let liveBooking=false;
if(validUrl(config.bookingUrl)){const u=new URL(config.bookingUrl);if(/(^|\.)yclients\.(ru|com)$/.test(u.hostname)){liveBooking=true;const a=document.querySelector('#booking-link');a.href=u.href;a.hidden=false;document.querySelector('#booking-description').textContent='Выберите услугу, дату и свободное время в официальной форме Yclients. Подтверждение записи вы получите от сервиса.'}}
const scenes={overview:{src:'interior-wide.jpeg',title:'Общий взгляд',text:'Дерево, камень и вода в одном пространстве.',number:'01'},lounge:{src:'lounge.jpeg',title:'Место для разговора',text:'Натуральное дерево, мягкий свет и спокойный ритм.',number:'02'},water:{src:'water.jpeg',title:'На контрасте ощущений',text:'Прохлада воды в окружении тёплых фактур.',number:'03'},stone:{src:'stone.jpeg',title:'Тепло в деталях',text:'Рельеф камня. Янтарный свет. Живая зелень.',number:'04'}};
const sceneImage=document.querySelector('#scene-image');
document.querySelectorAll('[data-scene]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.scene,s=scenes[key];sceneImage.style.backgroundImage=`url('assets/${s.src}')`;sceneImage.dataset.view=key;sceneImage.setAttribute('aria-label',s.title);document.querySelector('#scene-title').textContent=s.title;document.querySelector('#scene-text').textContent=s.text;document.querySelector('#scene-number').textContent=s.number+' / 04';document.querySelectorAll('.scene-tabs button').forEach(t=>t.setAttribute('aria-pressed',String(t.dataset.scene===key)));document.querySelector('.hotspots').hidden=key!=='overview';document.querySelector('#zoom').value=100;sceneImage.style.setProperty('--zoom',1)}));
document.querySelector('#zoom').addEventListener('input',e=>sceneImage.style.setProperty('--zoom',Number(e.target.value)/100));
document.querySelector('#light').addEventListener('click',e=>{const dim=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',String(dim));e.currentTarget.textContent=dim?'Вернуть свет':'Приглушить свет';sceneImage.style.setProperty('--light',dim?.6:1)});
const explorer=document.querySelector('#explorer'),expand=document.querySelector('#expand');
function closeExpanded(){explorer.classList.remove('expanded');document.body.style.overflow='';expand.setAttribute('aria-label','Развернуть просмотр');expand.textContent='⛶'}
expand.addEventListener('click',()=>{if(explorer.classList.contains('expanded')){closeExpanded();return}explorer.classList.add('expanded');document.body.style.overflow='hidden';expand.textContent='×';expand.setAttribute('aria-label','Свернуть просмотр');expand.focus()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeExpanded();if(e.key==='Tab'&&explorer.classList.contains('expanded')){const items=[...explorer.querySelectorAll('button')].filter(b=>!b.closest('[hidden]'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const point=config.entrance||config.location;
if(point){document.querySelector('#google-link').href=validUrl(config.googlePlaceUrl)||`https://www.google.com/maps/dir/?api=1&destination=${point.lat},${point.lng}&travelmode=driving`;document.querySelector('#yandex-link').href=validUrl(config.yandexPlaceUrl)||`https://yandex.by/maps/?rtext=~${point.lat},${point.lng}&rtt=auto&z=17`}
document.querySelector('#copy-address').addEventListener('click',async()=>{const text=config.address+'; въезд со стороны леса. '+point.lat+', '+point.lng;try{await navigator.clipboard.writeText(text);document.querySelector('#copy-status').textContent='Адрес и ориентир скопированы.'}catch{document.querySelector('#copy-status').textContent=text}});
for(const photo of config.guestPhotos||[]){if(!photo.src||!photo.alt)continue;const fig=document.createElement('figure'),img=document.createElement('img'),cap=document.createElement('figcaption');img.src=photo.src;img.alt=photo.alt;img.loading='lazy';cap.textContent=photo.caption||'';fig.append(img,cap);document.querySelector('#guest-gallery').append(fig);document.querySelector('#guest-section').hidden=false}
if(!liveBooking){document.querySelector('#booking-description').textContent='Демонстрация онлайн-записи. Услуги и время приведены для примера; заявка не отправляется.';document.querySelector('#booking-close').hidden=true;const panel=document.createElement('div');panel.id='booking-demo';booking.append(panel)}
const bookingState={format:'Банный отдых',date:'',time:'14:00'};
function localDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function renderBooking(step){const panel=document.querySelector('#booking-demo');if(!panel)return;const min=localDate(new Date());if(!bookingState.date||bookingState.date<min)bookingState.date=min;panel.replaceChildren();const progress=document.createElement('p');progress.className='demo-progress';progress.textContent=step===3?'ДЕМОНСТРАЦИЯ ЗАВЕРШЕНА':`ШАГ ${step+1} ИЗ 3 · ДЕМО`;panel.append(progress);
 const title=document.createElement('h3');title.tabIndex=-1;title.textContent=['Выберите формат','Выберите дату и время','Ваш выбор','Так будет выглядеть итог'][step];panel.append(title);
 function button(label,fn,secondary=false){const b=document.createElement('button');b.className='button'+(secondary?' secondary':'');b.textContent=label;b.onclick=fn;panel.append(b);return b}
 if(step===0){const options=document.createElement('div');options.className='demo-options';for(const value of ['Банный отдых','Отдых для двоих','Встреча с друзьями']){const b=document.createElement('button');b.className='demo-option';b.textContent=value;b.setAttribute('aria-pressed',String(bookingState.format===value));b.onclick=()=>{bookingState.format=value;renderBooking(0)};options.append(b)}panel.append(options);button('Продолжить',()=>renderBooking(1))}
 if(step===1){const label=document.createElement('label');label.textContent='Дата визита';label.className='date-label';const input=document.createElement('input');input.type='date';input.min=min;input.required=true;input.value=bookingState.date;input.oninput=()=>bookingState.date=input.value;label.append(input);panel.append(label);const options=document.createElement('div');options.className='demo-times';for(const value of ['10:00','12:00','14:00','16:00','18:00','20:00']){const b=document.createElement('button');b.className='demo-option';b.textContent=value;b.setAttribute('aria-pressed',String(bookingState.time===value));b.onclick=()=>{bookingState.time=value;options.querySelectorAll('button').forEach(t=>t.setAttribute('aria-pressed',String(t===b)))};options.append(b)}panel.append(options);button('Посмотреть итог',()=>{if(input.reportValidity())renderBooking(2)});button('Назад',()=>renderBooking(0),true)}
 if(step>=2){const summary=document.createElement('p');summary.className='demo-summary';summary.textContent=bookingState.format+' · '+new Date(bookingState.date+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})+' · '+bookingState.time;panel.append(summary);const note=document.createElement('p');note.textContent=step===2?'Это пример сценария. Указанное время не отражает реальную доступность.':'Заявка не отправлена, время не забронировано. После подключения Yclients здесь будет настоящая запись и подтверждение от сервиса.';panel.append(note);if(step===2){button('Завершить демо',()=>renderBooking(3));button('Изменить',()=>renderBooking(1),true)}else button('Вернуться на сайт',()=>booking.close())}
 title.focus({preventScroll:true});
}

if(validUrl(config.instagramUrl)){const u=new URL(config.instagramUrl);if(/(^|\.)instagram\.com$/.test(u.hostname)){for(const el of document.querySelectorAll('#instagram-link,#footer-instagram,.instagram-nav')){el.href=u.href;el.target='_blank';el.rel='noopener';el.hidden=false}document.querySelector('#instagram-placeholder').hidden=true;document.querySelector('#instagram-status').textContent='@'+u.pathname.split('/').filter(Boolean)[0]}}

document.querySelectorAll('[data-map-view]').forEach(button=>button.addEventListener('click',()=>{const isMap=button.dataset.mapView==='map';document.querySelector('#route-scheme').hidden=isMap;const map=document.querySelector('#map');map.hidden=!isMap;if(isMap&&!map.src)map.src=map.dataset.src;document.querySelectorAll('[data-map-view]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)))}));
