(() => {
 const root=document.documentElement,reduced=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover: hover) and (pointer: fine)');
 const toggle=document.querySelector('#motion-toggle'),hero=document.querySelector('.hero'),heroImage=document.querySelector('.hero-image'),explorer=document.querySelector('.explorer'),scene=document.querySelector('.scene-image'),header=document.querySelector('.header');
 let active=!reduced.matches,userChoice=null,raf=0,scrollDirty=true,region=null,bounds=null;
 const target={x:0,y:0},current={x:0,y:0};
 function reset(){for(const [el,keys] of [[heroImage,['--camera-x','--camera-y']],[scene,['--scene-x','--scene-y']]])for(const key of keys)el.style.setProperty(key,'0px')}
 function setMode(on){active=on;root.classList.toggle('motion-on',on);root.classList.toggle('motion-off',!on);toggle.setAttribute('aria-pressed',String(on));toggle.setAttribute('aria-label',on?'Отключить анимации':'Включить анимации');toggle.querySelector('.motion-icon').textContent=on?'Ⅱ':'▷';if(!on)reset();schedule()}
 toggle.addEventListener('click',()=>{userChoice=!active;setMode(userChoice)});reduced.addEventListener('change',()=>{if(userChoice===null)setMode(!reduced.matches)});
 const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}})},{threshold:.05});
 document.querySelectorAll('.section-head,.plan-card,.directions,.faq-list').forEach(e=>{e.classList.add('reveal');observer.observe(e)});
 function schedule(){if(!raf&&!document.hidden)raf=requestAnimationFrame(frame)}
 function frame(){raf=0;if(scrollDirty){const max=root.scrollHeight-innerHeight;root.style.setProperty('--reading',max>0?scrollY/max:0);header.classList.toggle('scrolled',scrollY>45);scrollDirty=false}if(active&&fine.matches&&region){current.x+=(target.x-current.x)*.1;current.y+=(target.y-current.y)*.1;const x=Math.max(-1,Math.min(1,(current.x-bounds.left)/bounds.width*2-1)),y=Math.max(-1,Math.min(1,(current.y-bounds.top)/bounds.height*2-1));const el=region===hero?heroImage:scene,prefix=region===hero?'--camera':'--scene';el.style.setProperty(prefix+'-x',`${-x*9}px`);el.style.setProperty(prefix+'-y',`${-y*6}px`);if(Math.abs(target.x-current.x)>.1||Math.abs(target.y-current.y)>.1)schedule()}}
 [hero,explorer].forEach(el=>{el.addEventListener('pointerenter',e=>{if(!active||!fine.matches)return;region=el;bounds=el.getBoundingClientRect();target.x=current.x=e.clientX;target.y=current.y=e.clientY;schedule()});el.addEventListener('pointermove',e=>{if(!active||!fine.matches)return;region=el;bounds=el.getBoundingClientRect();target.x=e.clientX;target.y=e.clientY;schedule()});el.addEventListener('pointerleave',()=>{region=null;reset()})});
 document.addEventListener('scroll',()=>{scrollDirty=true;if(region)bounds=region.getBoundingClientRect();schedule()},{passive:true});addEventListener('resize',()=>{scrollDirty=true;if(region)bounds=region.getBoundingClientRect();schedule()},{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else{scrollDirty=true;schedule()}});setMode(active);
})();
